name: KitPvp
version: '${project.version}'
main: uk.lewisl.kitpvp.KitPvp
api-version: 1.19
authors: [ storm0chaser ]
description: kit pvp plugin i guess
website: lewisl.uk


commands:
  kit:
    description: get ur kit looser
    usage: /kit
    aliases:
      - kits
  kitdelete:
    description: deletes a kit
    usage: /kitdelete (name)
    aliases:
      - kitdel
      - kitremove
      - kitrem
  kitcreate:
    description: create a kit
    usage: /kitcreate (name)
    aliases:
      - kitsave
  kitpvp:
       description: main command for this plugin
       usage: /kitpvp
       aliases:
         - kp
  coins:
    description: get your or another players coins
    usage: /coins
    aliases: [bal, coins, coin, balance]

  stats:
    description: get the stats of yourself or another player
    usage: /stats

  combattag:
    description: check if youre in combat
    usage: /combattag
    aliases: [ct]